# Generated by Django 5.0.7 on 2024-08-07 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
