# Generated by Django 5.0.7 on 2024-08-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_comment_likes_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
    ]
